### ISSUE TITLE
Can not save the result from docker

### ISSUE THREAD

**Issue by i19870503** [nucleosome-dynamics/docker#1]
I use the docker image to run nucleosome-dynamics, but the result Rdata file can not save in  the data_dir in the first step. The code and info pasted below:
 

`# docker run  -v /home/zhongl/data/DNAseq/WGS/nucleosome-dynamics_docker_test/test:/data_dir  -v /home/zhongl/data/DNAseq/WGS/nucleosome-dynamics_docker_test/test/data/refGenomes:/public_dir  --privileged=true  mmbirb/nucldyn readBAM --input data/cellcycleG2_chrII.bam --output data/cellcycleG2_chrII.RData --type paired`

> ===================================================
> ===> Nucleosome Dynamics (docker version) v0.1 <===
> ===================================================
> 
> ===> Running readBAM <===
> 
> -- loading data/cellcycleG2_chrII.bam
> 
> reading file data/cellcycleG2_chrII.bam
> processing flags
> processing strand +
> processing strand -
> -- saving data/cellcycleG2_chrII.RData
> 
> Error in gzfile(file, "wb") : cannot open the connection
> Calls: save -> gzfile
> In addition: Warning message:
> In gzfile(file, "wb") :
> cannot open compressed file 'data/cellcycleG2_chrII.RData', probable reason 'Permission denied'
> Execution halted
> ERROR while running readBAM. Check the full report at 'stdout'

**Comment by lcodo** [comment]
Hi Liang,
I'm sorry, I cannot reproduce the error but it looks like a file's permission error. Your docker user is able to read files from 'data_dir' ( `/data_dir/data/cellcycleG2_chrII.bam` is correctly load), but you cannot write in there, as the output file (`/data_dir/data/cellcycleG2_chrII.RData`) cannot be created.

Could you double check the permissions for data_dir (`/home/zhongl/data/DNAseq/WGS/nucleosome-dynamics_docker_test/test`)? Notice that the user account running the container (usually "docker" user) should be able to write there.

Alternatively, you could tell the docker engine which user you want the container to be run with. So try  updating the "docker  run" command setting as '--user' an account with writing permission into 'data_dir'. You can check docker's documentation, but for instance, if you want to use the current user, the command should look more or less like this:
`docker run --user $(id -u):$(id -g) -v /home/zhongl/data/DNAseq/WGS/nucleosome-dynamics_docker_test/test:/data_dir -v /home/zhongl/data/DNAseq/WGS/nucleosome-dynamics_docker_test/test/data/refGenomes:/public_dir --privileged=true mmbirb/nucldyn readBAM --input /data_dir/data/cellcycleG2_chrII.bam --output /data_dir/data/cellcycleG2_chrII.RData --type paired`

By the way, I would recommend using absolute paths in all file paths (above  in `--input` and `--output`). This way you are sure in which folder you are working on.

I hope it helps,
laia

**Comment by i19870503** [comment]
Thanks very much, after adding `--user $id -u):$(id -g)` the script work well.
